version: '3'
services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    image: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    environment:
      DATABASE_URL: postgres
      APP_ID: 123
      APP_SECRET: secret

volumes:
  postgres:
