version: 2.0

jobs:
  test:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Build packages
          command: |
            # Generate Photon
            cd server
            yarn prisma:generate
            # Build
            cd ..
            yarn build
      - run: yarn test
      - run: yarn coverage
  publish:
    docker:
      - image: 'circleci/node:11.3.0'
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Setup NPM and Github credentials
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            git config --global github.token $GH_TOKEN
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_USER
      - run:
          name: Release packages
          command: npm run release

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
